[package]
name = "synth-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chargrid_wgpu = { path = "/Users/s/src/chargrid/wgpu" }
env_logger = "0.10"
synth_app = { path = "../synth-app" }
