[package]
name = "synth-sdl2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chargrid_sdl2 = { path = "/Users/s/src/chargrid/sdl2" }
env_logger = "0.10"
synth_app = { path = "../app" }
